/**
 * Topic List
 * */
export const UPDATE_TOPIC_LIST = 'UPDATE_TOPIC_LIST';

export const UPDATE_TOPIC_ACTIVE_GROUP_ID = 'UPDATE_TOPIC_ACTIVE_GROUP_ID';

export const UPDATE_ACTIVE_TOPIC = 'UPDATE_ACTIVE_TOPIC';