/**
 * Topic List
 * */
export const UPDATE_TOPIC_LIST = 'UPDATE_TOPIC_LIST';

export const UPDATE_TOPIC_ACTIVE_GROUP_ID = 'UPDATE_TOPIC_ACTIVE_GROUP_ID';

export const UPDATE_ACTIVE_ANALYTICS_TOPIC = 'UPDATE_ACTIVE_ANALYTICS_TOPIC';

export const UPDATE_ACTIVE_COMPARE_TOPIC = 'UPDATE_ACTIVE_COMPARE_TOPIC';

export const UPDATE_ACTIVE_SETTING_TOPIC = 'UPDATE_ACTIVE_SETTING_TOPIC';


/**
 * Analytics
 * */
export const UPDATE_TYPE = 'UPDATE_TYPE';

export const UPDATE_TIME_RANGE = 'UPDATE_TIME_RANGE';

export const UPDATE_SOURCE = 'UPDATE_SOURCE';

export const UPDATE_SUBTOPIC = 'UPDATE_SUBTOPIC';

export const UPDATE_DATE_CHANGE = 'UPDATE_DATE_CHANGE';

export const UPDATE_START = 'UPDATE_START';

export const UPDATE_END = 'UPDATE_END';

export const UPDATE_REFRESH_TOPIC = 'UPDATE_REFRESH_TOPIC';

export const UPDATE_RESET_SEARCH = 'UPDATE_RESET_SEARCH';

export const UPDATE_SUBTOPIC_ID = 'UPDATE_SUBTOPIC_ID';

export const UPDATE_TIME_POP_UP = 'UPDATE_TIME_POP_UP';

export const UPDATE_ADD_TOPIC = 'UPDATE_ADD_TOPIC';
/**
 * Compare
 **/
export const UPDATE_COMPARE_TYPE = 'UPDATE_COMPARE_TYPE';

export const UPDATE_COMPARE_TIME_RANGE = 'UPDATE_COMPARE_TIME_RANGE';

export const UPDATE_COMPARE_SOURCE = 'UPDATE_COMPARE_SOURCE';

export const UPDATE_COMPARE_SUBTOPIC = 'UPDATE_COMPARE_SUBTOPIC';

export const UPDATE_COMPARE_START = 'UPDATE_COMPARE_START';

export const UPDATE_COMPARE_END = 'UPDATE_COMPARE_END';

export const UPDATE_COMPARE_TIME_RANGE_STRING = 'UPDATE_COMPARE_TIME_RANGE_STRING';

export const UPDATE_COMPARE_SOURCE_COUNT = 'UPDATE_COMPARE_SOURCE_COUNT';

export const UPDATE_COMPARE_DATA_CHANGE = 'UPDATE_COMPARE_DATA_CHANGE';


/**
 * Export Images
 * */
export const INSERT_EXPORT_IMAGES = 'INSERT_EXPORT_IMAGES';

export const REMOVE_EXPORT_IMAGES = 'REMOVE_EXPORT_IMAGES';

//登陆页
export const LOGIN_STATE = 'LOGIN_STATE';

//header
export const HEADER_NAME='HEADER_NAME';